### ISSUE TITLE
Wrap up term 1 work checklist

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/pip-db#166]
# TODO
- [x] Make sure everything is super-well documented, this means: commented code (obviously), build scripts, planning documents, logbook etc. Make it easier to regain my bearings in second term after all the mince pies are gone (#189, #183).
- [x] Final meet and greet / review session with Darren (+ Fraser?) to discuss UI changes to homepage and backend design issues (do we even need floats anyway?).
- [x] Make a side-by-side comparison of D1 mockups and M1 implementation, noting differences and design decisions (#181).
- [x] Consider transitioning to a branching git model, instead of a rebasing one (#180).
- [x] Consider transitioning logbook from LaTeX to Markdown (#191).
- [x] Rename repository from protein-db to pip-db (#173).
- [x] Formalise and document the [versioning scheme](http://en.wikipedia.org/wiki/Software_versioning) (#189).
- [x] Formalise and document the version control scheme (branching model, commit message style, commit size, etc.).
- [x] Re-assign any still-open M1 issues to M2.
- [x] Close M1.
# Research Topics

These are some things to look at before the start of second term.
### Development and process
- ~~[Gitflow](https://github.com/nvie/gitflow)~~
- [Travis-ci](http://about.travis-ci.org/docs/user/languages/php/)
### Testing & debugging
- [PHPunit](http://phpunit.de/manual/current/en/index.html)
- [Xdebug](http://xdebug.org/)
### Application Frameworks
- [Zend Framework](http://framework.zend.com/manual/2.2/en/user-guide/overview.html)
- [Backbone](https://github.com/jashkenas/backbone)
- [AngularJS](https://github.com/angular/angular.js)
### Build system & tooling
- [Phing](http://www.phing.info/docs/stable/hlhtml/index.html#d5e500)
- [Grunt](http://gruntjs.com/sample-gruntfile)
- [Static source file analysis](http://stackoverflow.com/questions/378959/is-there-a-static-code-analyzer-like-lint-for-php-files)
### Back-end
- [MySQL-Query-Builder](https://github.com/indeyets/MySQL-Query-Builder/tree/master)
- [MySQL Workbench](http://www.mysql.com/products/workbench/)
