### ISSUE TITLE
OpenUP Iteration 2 Roadmap

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/pip-db#212]
The second iteration covers development work from week 11 through to the end of the week 18.
### Elaboration phase (week 11-14)
- **User testing** - obtain user feedback on the D1/M1 website implementation from Darren and Fraser.
- **Meeting Stakeholders** - meet with Darren for a review of the project progress, and to discuss the plan for the second iteration development.
- **First iteration review** - perform a review of the first iteration development, including a side-by-side comparison of the D1 design and M1 implementation (#181).
- **Software architecture planning** - produce a plan for the intended software architecture implementation for M2.
### Construction phase (week 12-24)
- **Artwork & assets** - generate all required site artwork, such as a main logo.
- **Templating engine** - implement a templating system as described in the software architecture plan.
- **Data tier development** - implement the data back-end, including parsing new data from file.
- **Application log tier development** - implement the controller aspects of the MVC architecture.
- **Presentation tier development** - implement the GUI front-end.
## Research Topics

These are some things to look at before the start of second term.
#### Development and process
- ~~[Gitflow](https://github.com/nvie/gitflow)~~ (done)
- ~~[Travis-ci](http://about.travis-ci.org/docs/user/languages/php/)~~ (done)
#### Testing & debugging
- ~~[PHPunit](http://phpunit.de/manual/current/en/index.html)~~ (no longer relevant)
- ~~[Xdebug](http://xdebug.org/)~~ (no longer relevant)
- ~~[Midje](https://github.com/marick/Midje)~~
#### Application Frameworks
- ~~[Zend Framework](http://framework.zend.com/manual/2.2/en/user-guide/overview.html)~~ (no longer relevant)
- [Backbone](https://github.com/jashkenas/backbone)
- [AngularJS](https://github.com/angular/angular.js)
#### Build system & tooling
- ~~[Phing](http://www.phing.info/docs/stable/hlhtml/index.html#d5e500)~~ (no longer relevant)
- [Grunt](http://gruntjs.com/sample-gruntfile)
- ~~[Static source file analysis](http://stackoverflow.com/questions/378959/is-there-a-static-code-analyzer-like-lint-for-php-files)~~ (no longer relevant)
- ~~[marginalia](https://github.com/gdeer81/marginalia)~~
#### Back-end
- ~~[MySQL-Query-Builder](https://github.com/indeyets/MySQL-Query-Builder/tree/master)~~ (no longer relevant)
- ~~[MySQL Workbench](http://www.mysql.com/products/workbench/)~~ (no longer relevant)
### D2 (week 13)

The user interaction design should be the primary focus of this second iteration, with many of the common tasks (searching for a result, looking up a record, etc.) being more tightly defined.
1. An interactive prototype which implements common site tasks: logging in and out using credentials, searching for a record by protein name, searching records from a specific source, searching for records in a pI range, performing an advanced search, adding a new record, uploading a new dataset.
2. A set of interaction mock-ups for ‘edge case’ or uncommon events: an error on the server-side, performing a search which returns no results, attempting to log in with incorrect credentials.
### M2 (week 18)

By week 18 the software architecture and choice of technologies should have been fully realised, and the functional backend of the majority of use-cases should have been implemented, along with good test coverage of each.
1. A software design which stipulates the final decision on which technologies will be used.
2. An architectural design which covers the full model view controller stack and components of each.
3. A test harness and accompanying automated unit tests with full coverage of the API under common states.

![mvc architecture](https://f.cloud.github.com/assets/1636663/1726735/7258b076-6294-11e3-9de4-d5aeab713731.png)
### Functional requirements
- [x] Support for storing numerical values in the back-end for E.C., pI, molecular weight, and temperature properties.
- [x] Front-end support for searching by numerical values for E.C., pI, molecular weight, and temperature properties in the dataset, both as exact values and in ranges.
- [x] Support for tracking and auditing user behaviour on the public website, and a means for collecting and storing this usage data.
### Non-functional requirements
- [x] A first iteration review document containing a side-by-side comparison of the D1 design and M1 implementation (#181).
- [x] A second iteration design document containing improved designs for the site and full use-case coverage in the interaction design (#112).
- [x] A test harness and required infrastructure for testing PHP application tier logic.
- [ ] A test harness and required infrastructure for testing MySQL data tier logic.
- [ ] A browser automation test harness and infrastructure for front-end testing.
- [x] An object orientated PHP back-end, with no static/global methods.
- [x] Unit tests for the PHP back-end, with full branch coverage and error case testing.
- [ ] Automated browser front-end tests for the common site tasks identified in D1.
- [x] Support for automatically generating API documentation from source code.
- [x] API documentation for the application tier logic.
